export const extrasCosts = [
  {
    item_id: 12,
    item_name: 'Omelette',
    mess_id: 9,
    cost_per_item: 9,
    qty_sold: 100,
    total_cost: 900,
  },
  {
    item_id: 13,
    item_name: 'Boiled Egg',
    mess_id: 9,
    cost_per_item: 8,
    qty_sold: 100,
    total_cost: 800,
  },
  {
    item_id: 14,
    item_name: 'Paneer Bhurji',
    mess_id: 9,
    cost_per_item: 20,
    qty_sold: 100,
    total_cost: 2000,
  },
  {
    item_id: 15,
    item_name: 'Chilli Paneer',
    mess_id: 9,
    cost_per_item: 35,
    qty_sold: 100,
    total_cost: 3500,
  },
  {
    item_id: 16,
    item_name: 'Milk',
    mess_id: 9,
    cost_per_item: 12,
    qty_sold: 100,
    total_cost: 1200,
  },
  {
    item_id: 17,
    item_name: 'Rasgulla',
    mess_id: 9,
    cost_per_item: 14,
    qty_sold: 100,
    total_cost: 1400,
  },
];
