export const meals = [
  {
    mess_id: 9,
    meal_date: "2022-03-01",
    meal_time: 'Breakfast',
    menu_id: 'JKSHJKHDKF',
    contents: '123',
    total_cost: 5000,
  },
  {
    mess_id: 9,
    meal_date: "2022-03-01",
    meal_time: 'Lunch',
    menu_id: 'JKSHJKHDKF',
    contents: '123',
    total_cost: 5200.3,
  },
  {
    mess_id: 9,
    meal_date: "2022-03-01",
    meal_time: 'Dinner',
    menu_id: 'JKSHJKHDKF',
    contents: '123',
    total_cost: 2053.4,
  },
  {
    mess_id: 9,
    meal_date: "2022-03-02",
    meal_time: 'Breakfast',
    menu_id: 'JKSHJKHDKF',
    contents: '123',
    total_cost: null,
  },
  {
    mess_id: 9,
    meal_date: "2022-03-02",
    meal_time: 'Lunch',
    menu_id: 'JKSHJKHDKF',
    contents: '123',
    total_cost: null,
  },
  {
    mess_id: 9,
    meal_date: "2022-03-02",
    meal_time: 'Dinner',
    menu_id: 'JKSHJKHDKF',
    contents: '123',
    total_cost: null,
  },
]
